name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  - main
  - develop

pr:
  - main
  - develop

pool:
  vmImage: ubuntu-latest
  
steps:
  - script: docker ps
#  - uses: epeisach/rabbitmq-test-action@main
#        displayName: RUn RabbitMq
