name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  - main
  - develop

pr:
  - main
  - develop

jobs:
  - job: foo
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - uses: epeisach/rabbitmq-test-action@main
        displayName: RUn RabbitMq
      - run: |
          docker ps
        displayName: Ensure running          
          
