name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  - main
  - develop

pr:
  - main
  - develop

pool:
  vmImage: ubuntu-latest
  
steps:
  - script: docker run -d -p 5672:5672: -p 5673:5673 rabbitmq:3
    displayName: Start rabbitmq
  - script: docker ps
#  - uses: epeisach/rabbitmq-test-action@main
#        displayName: RUn RabbitMq
