name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  - main
  - develop

pr:
  - main
  - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: epeisach/rabbitmq-test-action@main
#        displayName: RUn RabbitMq
