on: [push]

jobs:
  start_docker_job:
    runs-on: ubuntu-latest
    name: Simple test of docker
    steps:
      - name: RabbitMq action step
        id: rbmq
        uses: epeisach/rabbitmq-test-action@main
      - name: See what is happening
        script: docker ps
        
        
